### ISSUE TITLE
isNumeric is not completely equal to $.isNumeric

### ISSUE THREAD

**Issue by woodbrick** [nefe/You-Dont-Need-jQuery#164]
This article is very helpful to understand native Javascript
But I found some issues to be fixed

```$.isNumeric(new Number(1))  // true```

```
function isNumeric(value) {
  var type = typeof value;

  return (type === 'number' || type === 'string') && !Number.isNaN(value - Number.parseFloat(value));
}
```
```isNumeric(new Number(1))  // false```

I found another way to check numeric in
[https://gist.github.com/pinalbhatt/9672790](url)

```
function isNumeric(n) {
  return !isNaN(parseFloat(n)) && isFinite(n);
}
```
this function passed all cases in jquery public document:
[http://api.jquery.com/jQuery.isNumeric/](url)

**Comment by camsong** [comment]
Yep, this should be better, can you make a PR?

**Comment by woodbrick** [comment]
Of cause, and should I update chinese edition only or all languages for this code ?
