### ISSUE TITLE
unwrap方法不太对

### ISSUE THREAD

**Issue by sunchenguang** [nefe/You-Dont-Need-jQuery#167]
这个方法是将匹配元素集合的父级元素删除，保留自身（和兄弟元素，如果存在）在原来的位置。

但是在本文档中，它是将el的子元素放到el的父元素中，然后删除el。并不是删除el的父元素，与目的不一致

**Comment by item4** [comment]
Please use English. almost developer in GitHub can not read Chinese.

**Comment by sunchenguang** [comment]
unwrap method is incorrect。it's result is not consistent with jQuery unwrap method

**Comment by camsong** [comment]
@sunchenguang You are right, can you help to make an alternative? thanks
