### ISSUE TITLE
8.3 FadeIn and FadeOut JS equivalents will not work as intended

### ISSUE THREAD

**Issue by sahibjotsaggu** [nefe/You-Dont-Need-jQuery#180]
```
// jQuery
$el.fadeIn(3000);
$el.fadeOut(3000);

// Native
el.style.transition = 'opacity 3s';
// fadeIn
el.style.opacity = '1';
el.style.display = ''|'inline'|'inline-block'|'inline-table'|'block';
// fadeOut
el.style.opacity = '0';
el.style.display = 'none';
```

The JS equivalents will not actually work as intended because the `el.style.display` line will execute right after the `el.style.opacity` line without any delay. (as seen here: https://codepen.io/anon/pen/BYEpJV).

The correct way to do this is by wrapping the `el.style.display` around a `setTimeout()` function:

```
// fadeOut
el.style.opacity = 0;
setTimeout(function() {
  el.style.display = 'none';
}, 3000);
```

**Comment by CarloMartini** [comment]
My bad... You're right on the problem, but I would suggest a more precise alternative to setTimeout, that is the transitionend event:

```
// fadeOut

el.addEventListener("transitionend", function (event) {
        el.style.display = 'none';
}, false);
el.style.opacity = '0';
```

I'll open a PR later, to fix both fadeOut and fadeIn.

**Comment by sahibjotsaggu** [comment]
Great! I was not aware of that event.

**Comment by arunguptacatalystone** [comment]
For me transitionend didn't work.
This one worked though :
`el.addEventListener("webkitAnimationEnd", function (event) {
      el.style.display = 'none';
    }, false);`
