### ISSUE TITLE
$el.remove() can be improved

### ISSUE THREAD

**Issue by qgustavor** [nefe/You-Dont-Need-jQuery#212]
[ChildNode.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) is a simpler and modern way to remove element nodes:

```javascript
// jQuery
$el.remove();

// Native - IE10+
el.parentNode.removeChild(el);

// Native - Only latest, NO IE
el.remove();
```

**Comment by Melonxx** [comment]
pr

**Comment by camsong** [comment]
Merged in https://github.com/nefe/You-Dont-Need-jQuery/pull/219
