### ISSUE TITLE
Why manipulate DOM directly?

### ISSUE THREAD

**Issue by rbluethl** [nefe/You-Dont-Need-jQuery#214]
Hello there,

from this project's README:
> In the meantime, thanks to the spread of frontend libraries such as React, Angular and Vue, manipulating the DOM directly becomes anti-pattern, so that jQuery usage has never been less important.

You clearly state that manipulating the DOM directly is an anti-pattern. While I understand the motivation to not use jQuery for "simple" DOM operations, how does using native elements to manipulate the DOM differ from using jQuery? Isn't it an anti-pattern to manipulate the DOM -- regardless of the underlying framework/technology?

No criticism here, I'm just asking out of curiosity.

Ronald

**Comment by camsong** [comment]
What I mean is:
Mostly manipulating the DOM directly becomes anti-pattern, and jQuery is good at manipulating the DOM
-> so jQuery is not so important
-> so you don't need to import extra ~100KB for jQuery
-> but in some corner case, you still need to manipulate the DOM, so just use the native API.
-> this docs meet your need.
