### ISSUE TITLE
Doesn't IE not support arrow functions =>

### ISSUE THREAD

**Issue by raymondpittman** [nefe/You-Dont-Need-jQuery#216]
Just stating this incase it does not, good tutorial.

**Comment by CITguy** [comment]
Correct. Arrow functions are part of ES2015 (a.k.a. ES6) and [unsupported by IE](https://kangax.github.io/compat-table/es6/#test-arrow_functions).

**Comment by raymondpittman** [comment]
I mentioned because of the IE support icon on your readme.

**Comment by raymondpittman** [comment]
I can write you a simple => arrow to function script.

**Comment by camsong** [comment]
@raymondpittman  PR is welcome, thanks.
