### ISSUE TITLE
JS version of :empty selector

### ISSUE THREAD

**Issue by drewbaker** [nefe/You-Dont-Need-jQuery#227]
Would love to see a JS version of how to select all empty elements in JS, as this works: https://api.jquery.com/empty-selector/

**Comment by zdivozzo** [comment]
:empty is just a css selector, so you should be able to just do this `document.querySelectorAll('*:empty')` to get a list of all empty elements.

**Comment by drewbaker** [comment]
Oh cool! Didn't know that! Thanks.
