### ISSUE TITLE
one-liner statement everywhere

### ISSUE THREAD

**Issue by the-liquid-metal** [nefe/You-Dont-Need-jQuery#235]
one-liner statement is more attractive than multi-liner, and closer to jquery style.
also:
* remove parentheses in closure param if possible in order to remove distraction.
* convert function to bare statemant.
* use ternary operator
* more pragmatic example

All previous siblings (bare statemant):
```[...el.parentNode.children].filter((item, idx, self) => idx < self.indexOf(el) && item.matches($selector))```

All next siblings (bare statemant):
```[...el.parentNode.children].filter((item, idx, self) => idx > self.indexOf(el) && item.matches($selector))```

FadeToggle (ternary operator):
```el.style.opacity = (opacity === "1") ? "0" : "1";```

isEmptyObject (a pragmatic way):
```
// usage in IF statement
if (Object.keys(obj).length) {
    // ...
}
```
note: in most case isEmptyObject is used in IF statement. ```Object.keys``` returns array. ```array.length``` is always number. 0 is converted to false, otherwise true. there is no need to create function in order to replace isEmptyObject.

**Comment by camsong** [comment]
Looks good, could you make a PR?
