### ISSUE TITLE
Any tips on responsive layout / adaptive layout

### ISSUE THREAD

**Issue by BdR76** [nefe/You-Dont-Need-jQuery#245]
jQuery also has lots of plug-ins for adaptive/responsive layouts. So to resize DOM elements and fonts to fit different screen resolutions.

Maybe you can add tips on how to do a responsive layout / adaptive layout natively, maybe using just CSS? I found [this article](https://www.creativebloq.com/how-to/build-adaptive-layouts-without-media-queries) quite helpful.

**Comment by nidhiarya1245** [comment]
Well we can't completely remove media query. But we can minimize media queries. and for responsive flex is best option with VW for font. Because flex give more freedom then using css framework.
 Also, VH and VW units can cause issues on iOS devices.
