### ISSUE TITLE
Info about querySelectorAll is not correct

### ISSUE THREAD

**Issue by alexkuzmin** [nefe/You-Dont-Need-jQuery#247]
```js
  // jQuery
  $('selector');

  // Native
  document.querySelectorAll('selector');
  ```
But querySelectorAll is very limited and not really an alternative to what jQuery has, e.g. $('[attribute]'), $('.class > .child:eq(5)') and a lot of other possible cases are much more complicated to overwrite using vanilla JS.

**Comment by camsong** [comment]
Yep, added a notice in the top. https://github.com/nefe/You-Dont-Need-jQuery/commit/641b287135b0dfd955db28ddf2d629747da14875
